// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBp6CGNgItxPhyKnRPHleaBuFXkUTUxpKc',
    appId: '1:459049398921:web:2f10a834dbfc032af34c58',
    messagingSenderId: '459049398921',
    projectId: 'animal-warfare-game',
    authDomain: 'animal-warfare-game.firebaseapp.com',
    storageBucket: 'animal-warfare-game.firebasestorage.app',
    measurementId: 'G-2QDB9C9CZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtbgxNcAD5e6nz0gE1fYSeLhmLgnwn2yY',
    appId: '1:459049398921:android:356a73955719fb90f34c58',
    messagingSenderId: '459049398921',
    projectId: 'animal-warfare-game',
    storageBucket: 'animal-warfare-game.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRfIXqffrMu85-c7iU1s7-0wRLP8mhFu8',
    appId: '1:459049398921:ios:1fcc96c1faac7a2cf34c58',
    messagingSenderId: '459049398921',
    projectId: 'animal-warfare-game',
    storageBucket: 'animal-warfare-game.firebasestorage.app',
    iosBundleId: 'com.example.animalWarfare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRfIXqffrMu85-c7iU1s7-0wRLP8mhFu8',
    appId: '1:459049398921:ios:1fcc96c1faac7a2cf34c58',
    messagingSenderId: '459049398921',
    projectId: 'animal-warfare-game',
    storageBucket: 'animal-warfare-game.firebasestorage.app',
    iosBundleId: 'com.example.animalWarfare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBp6CGNgItxPhyKnRPHleaBuFXkUTUxpKc',
    appId: '1:459049398921:web:cf1e03c182e0eb8ff34c58',
    messagingSenderId: '459049398921',
    projectId: 'animal-warfare-game',
    authDomain: 'animal-warfare-game.firebaseapp.com',
    storageBucket: 'animal-warfare-game.firebasestorage.app',
    measurementId: 'G-V8V89Q8YG1',
  );
}
