import json

categories = [
    'ECOLOGY', 'SCIENCE', 'BATTLE META', 'EXPLORATION', 'TAXONOMY', 
    'CONSERVATION', 'BIOMETRICS', 'WEATHER', 'DISCOVERY', 'STATISTICS', 
    'PROFILE', 'OPINION', 'GENERAL'
]

templates = {
    'ECOLOGY': [
        "The {habitat} ecosystem wouldn't be the same without {name}.",
        "I saw a {name} in the {habitat} just yesterday!",
        "Nature is truly amazing. The {name} is a vital part of it.",
        "We need to protect the {habitat} for creatures like the {name}.",
        "Is it true that {name} populations are rising?",
        "I love how {name} interacts with its environment.",
        "The {habitat} is so beautiful, especially with {name} around.",
        "Sustainable {habitat} management is key for {name} survival.",
        "Interesting observation about the {name}'s role in the food chain.",
        "I've always wondered how {name} survives the {habitat} climate.",
        "Great insights on the {habitat} biodiversity.",
        "The {name} is such a resilient species.",
        "I'm worried about the impact of climate change on {name}.",
        "We should set up more protected areas in the {habitat}.",
        "The {name} is a perfect example of adaptation.",
        "How does {name} affect the other species in {habitat}?",
        "Beautifully written article about the {habitat} wild.",
        "I've been studying {name} for years, and they still surprise me.",
        "The {habitat} balance is delicate, {name} is crucial.",
        "Protecting {name} means protecting the whole {habitat}.",
        "Is there a migration cycle for {name} in {habitat}?",
        "Such a fascinating creature, the {name}.",
        "I hope to see a {name} in the wild someday.",
        "The {habitat} diversity is what makes this game great.",
        "Let's focus more on {name} conservation efforts.",
        "The {name} is truly the king of the {habitat}.",
        "Incredible photos of the {name}!",
        "Does {name} have any natural predators in {habitat}?",
        "I've noticed {name} behavior changing lately.",
        "The {habitat} is the best biome for {name}.",
        "We need more research on {name} breeding habits.",
        "The {name} is so iconic for the {habitat}.",
        "I could spend all day watching {name} in {habitat}.",
        "The {habitat} is lucky to have {name}.",
        "Every {name} matters for the {habitat}.",
        "The {name} story is so inspiring.",
        "Can {name} survive outside of {habitat}?",
        "The {habitat} food web is so complex.",
        "I'm glad to see {name} getting some attention.",
        "The {name} is a true survivor.",
        "What's the best time to spot {name} in {habitat}?",
        "The {habitat} is full of surprises, like {name}.",
        "I've learned so much about {name} from this.",
        "The {name} is a master of camouflage in {habitat}.",
        "We should respect {name}'s space in the wild.",
        "The {habitat} belongs to {name} as much as anyone.",
        "Great work on documenting the {name}.",
        "The {name} is a legend of the {habitat}.",
        "I feel so connected to nature when I see {name}.",
        "The {habitat} is a sanctuary for {name}.",
        "Long live the {name} of the {habitat}!",
        "The {name} is a symbol of {habitat} strength.",
        "Never underestimate a {name} in the {habitat}."
    ],
    'SCIENCE': [
        "The genetic makeup of {name} is truly unique.",
        "Fascinating data on the {name}'s biology.",
        "The scientific community is buzzing about this {name} study.",
        "How does the {name} evolve in different {habitat} conditions?",
        "The {name} represents a major breakthrough in taxonomy.",
        "I'm interested in the metabolic rate of {name}.",
        "The {name} is a biological marvel.",
        "We need more laboratory data on {name} {drops}.",
        "The {name}'s adaptation to {habitat} is scientifically significant.",
        "Is the {name} related to other {animal_class} species?",
        "The cellular structure of {name} is worth investigating.",
        "What are the long-term effects of {habitat} on {name} DNA?",
        "The {name} provides key evidence for evolutionary theories.",
        "I'm impressed by the rigorous research on {name}.",
        "The {name}'s {rarity} status makes it a prime research subject.",
        "Can we replicate {name} traits in a controlled environment?",
        "The scientific name {scientific_name} is very fitting.",
        "I wonder if {name} has any unique chemical properties.",
        "The {name} is a bridge between species.",
        "We should analyze the {name}'s response to stimuli.",
        "The {name} is a treasure trove of biological data.",
        "How does the {name}'s brain function in {habitat}?",
        "The {name} is a testament to the power of evolution.",
        "I'm excited for the next paper on {name}.",
        "The {name} research is pushing the boundaries of science.",
        "What can we learn from {name}'s {drops}?",
        "The {name} is a complex organism indeed.",
        "I'm studying the {name}'s sensory organs.",
        "The {name} is a model for {habitat} adaptation.",
        "How does {name} communicate with its peers?",
        "The {name} is a biological masterpiece.",
        "We should investigate the {name}'s longevity.",
        "The {name} is a key species for science.",
        "I'm fascinated by the {name}'s growth rate.",
        "The {name} is a pioneer of the {habitat}.",
        "What's the genetic distance between {name} and its relatives?",
        "The {name} is a marvel of bio-engineering.",
        "We need to sequence the full genome of {name}.",
        "The {name} is a star of the scientific world.",
        "I'm looking forward to the {name} symposium.",
        "The {name} is a scientific icon.",
        "How does the {name} process energy in {habitat}?",
        "The {name} is a study in perfection.",
        "We should explore the {name}'s immune system.",
        "The {name} is a beacon of scientific discovery.",
        "I'm intrigued by the {name}'s behavior in labs.",
        "The {name} is a gift to researchers.",
        "What are the evolutionary origins of {name}?",
        "The {name} is a cornerstone of biological research.",
        "I'm dedicated to uncovering the secrets of {name}.",
        "The {name} is a scientific wonder.",
        "We must preserve {name} for future generations of scientists.",
        "The {name} is the future of biological exploration."
    ],
    'BATTLE META': [
        "Is {name} actually viable in the current meta?",
        "The {name} is a beast in {habitat} battles!",
        "I've been using {name} as my main and it's unstoppable.",
        "What's the best build for a {rarity} {name}?",
        "The {name} totally counters the current top tiers.",
        "Don't sleep on {name}, its speed is insane.",
        "How do I deal with a {name} in the {habitat}?",
        "The {name} is a must-have for any competitive team.",
        "I just won a tournament with {name}!",
        "The {name}'s stats are perfectly balanced for BATTLE.",
        "What's the best move for a {name} in {habitat}?",
        "The {name} is the ultimate glass cannon.",
        "I'm pairing {name} with a tank for the best results.",
        "The {name} meta is shifting, stay ahead!",
        "Is {name} worth the grind for its {rarity} status?",
        "The {name} is a game-changer on the battlefield.",
        "I've seen some crazy {name} plays recently.",
        "What are the best items for {name}?",
        "The {name} is a tactical genius's best friend.",
        "How does {name} perform in team battles?",
        "The {name} is a force to be reckoned with.",
        "I'm training my {name} to be the strongest.",
        "The {name} is a true warrior of the {habitat}.",
        "What's the best strategy against {name}?",
        "The {name} is a meta-defining species.",
        "I've noticed {name} is becoming very popular.",
        "The {name} is the key to victory.",
        "How do I maximize {name}'s potential?",
        "The {name} is a legend in the arena.",
        "I'm excited to see {name} in action.",
        "The {name} is a powerhouse in {habitat}.",
        "What's the most effective way to use {name}?",
        "The {name} is a top-tier contender.",
        "I've been theorycrafting with {name} all night.",
        "The {name} is a master of combat.",
        "How does {name} stack up against other {rarity} creatures?",
        "The {name} is a vital asset for any trainer.",
        "I'm impressed by {name}'s resilience in battle.",
        "The {name} is a star of the competitive scene.",
        "What's the best habitat for training {name}?",
        "The {name} is a battle-hardened veteran.",
        "I'm looking for a {name} with perfect stats.",
        "The {name} is a symbol of battle prowess.",
        "How do I unlock {name}'s full power?",
        "The {name} is a beacon of strength.",
        "I'm proud to have a {name} on my team.",
        "The {name} is a true champion.",
        "What are the best synergies for {name}?",
        "The {name} is a legend of the battlefield.",
        "I'm dedicated to mastering {name}.",
        "The {name} is a battle icon.",
        "We must respect the power of {name}!",
        "The {name} is the king of the arena."
    ],
    'EXPLORATION': [
        "I finally found a {name} in the {habitat}!",
        "Searching for {name} is the best part of the game.",
        "The {habitat} is full of hidden {name} spots.",
        "What's the rarest {name} variant you've seen?",
        "I've been exploring the {habitat} all day and found no {name}.",
        "The {name} is so hard to track in the wild.",
        "Any tips for finding {name} in the {habitat}?",
        "The {habitat} is a playground for {name} hunters.",
        "I love the thrill of the {name} chase.",
        "The {name} is the ultimate exploration prize.",
        "What's the best route for {name} spotting in {habitat}?",
        "I've mapped out all the {name} locations in {habitat}.",
        "The {name} is a master of hiding.",
        "I'm on a mission to find every {name} in the world.",
        "The {habitat} is so immersive when you're looking for {name}.",
        "I just discovered a new {name} nest!",
        "The {name} is a true explorer's companion.",
        "What gear do I need for {name} hunting in {habitat}?",
        "The {name} is a beacon for adventurers.",
        "I've seen some incredible sights while tracking {name}.",
        "The {habitat} is a mystery waiting to be solved, starting with {name}.",
        "I'm addicted to {name} exploration.",
        "The {name} is a symbol of discovery.",
        "What's your favorite memory of finding a {name}?",
        "The {name} is a legend of the unknown.",
        "I've travelled far and wide to find this {name}.",
        "The {habitat} is my favorite place to look for {name}.",
        "I'm building a collection of {name} from every biome.",
        "The {name} is a star of the exploration world.",
        "What's the most challenging {name} to find?",
        "The {name} is a reward for the persistent.",
        "I'm looking forward to my next {name} expedition.",
        "The {habitat} is a treasure map, and {name} is the X.",
        "I've found a secret {name} cache in {habitat}!",
        "The {name} is a true survivor of the wild.",
        "What's the best time of day to explore for {name}?",
        "The {name} is a beacon of the wilderness.",
        "I've documented over 100 {name} sightings.",
        "The {habitat} is a world of wonder with {name}.",
        "I'm a certified {name} tracker.",
        "The {name} is a symbol of the untamed.",
        "What's the furthest you've gone to find a {name}?",
        "The {name} is a star of the map.",
        "I'm dedicated to finding the rarest {name}.",
        "The {habitat} is a challenge, but {name} is worth it.",
        "I've seen {name} in places you wouldn't believe.",
        "The {name} is a legend of the frontier.",
        "What's the most exotic {habitat} you've found {name} in?",
        "The {name} is a beacon for the brave.",
        "I'm an expert at {name} location.",
        "The {habitat} is a story, and {name} is a chapter.",
        "I've found my first {name} and I'm hooked!",
        "The {name} is the heart of exploration."
    ],
    'TAXONOMY': [
        "The classification of {name} is quite controversial.",
        "I agree with the new {name} taxonomy.",
        "What's the scientific history of {name}?",
        "The {name} fits perfectly in the {animal_class} family.",
        "I'm interested in the lineage of {name}.",
        "The {name}'s name is a bit misleading, don't you think?",
        "How does {name} compare to its closest relatives?",
        "The taxonomy of {name} is a work in progress.",
        "I love the scientific name {scientific_name}!",
        "The {name} is a unique branch on the tree of life.",
        "What are the defining characteristics of {name}?",
        "The {name} is a model for taxonomic studies.",
        "I'm studying the fossil record of {name}.",
        "The {name} is a link to the past.",
        "How many sub-species of {name} are there?",
        "The {name} is a star of the museum.",
        "I'm building a database of {name} traits.",
        "The {name} is a beacon of biological order.",
        "What's the etymology of the name {name}?",
        "The {name} is a testament to the diversity of {animal_class}.",
        "I'm fascinated by the classification of {rarity} species like {name}.",
        "The {name} is a key to understanding evolution.",
        "What's the most unique thing about {name}'s taxonomy?",
        "The {name} is a legend of the biological world.",
        "I've been researching {name} ancestors for months.",
        "The {name} is a star of the library.",
        "What's the best book on {name} taxonomy?",
        "The {name} is a reward for the curious.",
        "I'm looking forward to the next {name} classification update.",
        "The {name} is a beacon of scientific naming.",
        "What's the genetic distance between {name} and other species?",
        "The {name} is a star of the lab.",
        "I'm an expert at {name} identification.",
        "The {name} is a symbol of biological complexity.",
        "What's the most surprising thing you've learned about {name}?",
        "The {name} is a legend of the science scene.",
        "I've documented over 50 {name} variants.",
        "The {name} is a star of the field guide.",
        "What's the best habitat for studying {name} taxonomy?",
        "The {name} is a beacon of scientific rigor.",
        "I'm dedicated to uncovering the origins of {name}.",
        "The {name} is a symbol of evolutionary history.",
        "What's the most common mistake in {name} classification?",
        "The {name} is a star of the academic world.",
        "I'm a certified {name} taxonomist.",
        "The {name} is a beacon of biological truth.",
        "What's the most rare {animal_class} you've seen?",
        "The {name} is a legend of the natural history museum.",
        "I'm fascinated by the {name}'s place in the world.",
        "The {name} is a star of the biological record.",
        "I've found a new way to classify {name}!",
        "The {name} is the heart of taxonomy."
    ],
    'CONSERVATION': [
        "We must protect the {name} at all costs.",
        "The {habitat} is in danger, and so is {name}.",
        "I'm volunteering for a {name} conservation project.",
        "What can we do to help the {name} in {habitat}?",
        "The {name} is a symbol of our commitment to nature.",
        "I'm donating to a {name} sanctuary.",
        "How many {name} are left in the wild?",
        "The {name} is a key species for the {habitat}'s health.",
        "I'm raising awareness for the {name}.",
        "The {name} is a beacon of hope for conservationists.",
        "What are the biggest threats to {name} in {habitat}?",
        "I've seen the impact of habitat loss on {name}.",
        "The {name} is a star of the environmental movement.",
        "I'm working on a {name} recovery plan.",
        "The {name} is a testament to our responsibility.",
        "What's the best way to support {name} protection?",
        "The {name} is a legend of the green world.",
        "I've been advocating for {name} for years.",
        "The {name} is a star of the nature reserve.",
        "What's the status of {name} on the endangered list?",
        "The {name} is a reward for the mindful.",
        "I'm looking forward to the next {name} conservation summit.",
        "The {name} is a beacon of wildlife protection.",
        "What's the most effective {name} conservation strategy?",
        "The {name} is a star of the wildlife fund.",
        "I'm an expert at {name} habitat restoration.",
        "The {name} is a symbol of environmental balance.",
        "What's the most inspiring {name} success story?",
        "The {name} is a legend of the conservation scene.",
        "I've documented the comeback of the {name}.",
        "The {name} is a star of the ecology blog.",
        "What's the best habitat for {name} reintroduction?",
        "The {name} is a beacon of sustainability.",
        "I'm dedicated to saving the {name}.",
        "The {name} is a symbol of nature's resilience.",
        "What's the most common threat to {name} today?",
        "The {name} is a star of the conservationist community.",
        "I'm a certified {name} protector.",
        "The {name} is a beacon of ecological integrity.",
        "What's the rarest {name} you've helped save?",
        "The {name} is a legend of the earth.",
        "I'm fascinated by the {name}'s ability to adapt to changes.",
        "The {name} is a star of the natural world.",
        "I've found a new way to help {name} thrive!",
        "The {name} is the heart of conservation."
    ],
    'BIOMETRICS': [
        "The {name}'s {weight} kg mass is impressive.",
        "Fascinating data on the {name}'s size.",
        "The {name} is a powerhouse of biometrics.",
        "How does the {name} maintain its weight in {habitat}?",
        "The {name} represents a major study in robustness.",
        "I'm interested in the BST of {name}.",
        "The {name} is a biological marvel of scale.",
        "We need more biometric data on {name}.",
        "The {name}'s {size} m stature is scientifically significant.",
        "Is the {name} the largest of its kind?",
        "The {name}'s stats are worth investigating.",
        "What are the long-term effects of {habitat} on {name} biometrics?",
        "The {name} provides key evidence for biometric theories.",
        "I'm impressed by the rigorous data on {name}.",
        "The {name}'s {rarity} status makes it a prime biometric subject.",
        "Can we replicate {name} growth in a controlled environment?",
        "The {name} is a star of the biometric record.",
        "I wonder if {name} has any unique physical properties.",
        "The {name} is a bridge between sizes.",
        "We should analyze the {name}'s response to growth.",
        "The {name} is a treasure trove of physical data.",
        "How does the {name}'s body function in {habitat}?",
        "The {name} is a testament to the power of biology.",
        "I'm excited for the next data set on {name}.",
        "The {name} research is pushing the boundaries of biometrics.",
        "What can we learn from {name}'s {weight}?",
        "The {name} is a complex organism physically.",
        "I'm studying the {name}'s growth patterns.",
        "The {name} is a model for {habitat} biometrics.",
        "How does {name} manage its energy levels?",
        "The {name} is a biological masterpiece of scale.",
        "We should investigate the {name}'s metabolic efficiency.",
        "The {name} is a key species for biometrics.",
        "I'm fascinated by the {name}'s strength-to-weight ratio.",
        "The {name} is a pioneer of the {habitat} physically.",
        "What's the biometric distance between {name} and its peers?",
        "The {name} is a marvel of physical engineering.",
        "We need to measure every {name} in the world.",
        "The {name} is a star of the biometric world.",
        "I'm looking forward to the {name} measurement guide.",
        "The {name} is a biometric icon.",
        "How does the {name} process food in {habitat}?",
        "The {name} is a study in physical perfection.",
        "We should explore the {name}'s muscle structure.",
        "The {name} is a beacon of biometric discovery.",
        "I'm intrigued by the {name}'s physical traits.",
        "The {name} is a gift to biometricians.",
        "What are the physical origins of {name}?",
        "The {name} is a cornerstone of biometric research.",
        "I'm dedicated to measuring the secrets of {name}.",
        "The {name} is a biometric wonder.",
        "We must preserve {name} data for future generations of biometricians.",
        "The {name} is the future of physical exploration."
    ],
    'WEATHER': [
        "The {name} seems to love the current {habitat} weather.",
        "How does the {name} react to storms in {habitat}?",
        "I've noticed {name} activity surges during rain.",
        "The {name} is a perfect weather indicator for {habitat}.",
        "I'm studying the impact of wind on {name} behavior.",
        "The {name} is a star of the meteorological report.",
        "What's the best weather for {name} spotting?",
        "I've seen {name} thriving in extreme heat.",
        "The {name} is a beacon of climate resilience.",
        "How does the {name} survive the cold in {habitat}?",
        "The {name} is a key species for weather research.",
        "I'm tracking {name} migrations based on weather patterns.",
        "The {name} is a star of the {habitat} sky.",
        "What's the relationship between {name} and humidity?",
        "The {name} is a testament to nature's adaptability.",
        "I've seen some incredible {name} weather events.",
        "The {name} is a reward for the weather-aware.",
        "I'm looking forward to the next {name} weather forecast.",
        "The {name} is a beacon of atmospheric research.",
        "What's the most surprising {name} weather behavior?",
        "The {name} is a star of the weather channel.",
        "I'm an expert at {name} climate analysis.",
        "The {name} is a symbol of weather balance.",
        "What's the most extreme weather you've seen {name} in?",
        "The {name} is a legend of the storm.",
        "I've documented {name} behavior in all seasons.",
        "The {name} is a star of the weather blog.",
        "What's the best weather for training {name}?",
        "The {name} is a beacon of seasonal change.",
        "I'm dedicated to understanding {name} and the weather.",
        "The {name} is a symbol of nature's moods.",
        "What's the most common weather-related {name} trait?",
        "The {name} is a star of the meteorological community.",
        "I'm a certified {name} weather tracker.",
        "The {name} is a beacon of climate data.",
        "What's the rarest {name} weather event you've seen?",
        "The {name} is a legend of the elements.",
        "I'm fascinated by the {name}'s reaction to lightning.",
        "The {name} is a star of the natural world in all weathers.",
        "I've found a new way to predict {name} behavior using weather!",
        "The {name} is the heart of weather observation.",
        "I love watching {name} during a {habitat} sunset.",
        "The {name} is a master of the elements.",
        "We should study {name} during the next solar eclipse.",
        "The {name} is a beacon of solar energy in {habitat}.",
        "How does {name} handle the {habitat} fog?",
        "The {name} is a star of the misty mornings.",
        "What's the best weather for {name} photography?",
        "The {name} is a legend of the overcast days.",
        "I'm fascinated by {name}'s behavior in the snow.",
        "The {name} is a star of the winter wonderland.",
        "We must respect the {name}'s weather wisdom.",
        "The {name} is the future of weather science."
    ],
    'DISCOVERY': [
        "I just discovered a new {name} variant!",
        "What's the most rare {name} you've found?",
        "The {habitat} is full of {name} surprises.",
        "I've been looking for {name} for ages and finally found one!",
        "The {name} is the ultimate discovery.",
        "Any tips for uncovering {name} in the {habitat}?",
        "I love the thrill of {name} discovery.",
        "The {name} is a beacon for curious minds.",
        "I just found a hidden {name} area!",
        "The {name} is a star of the discovery channel.",
        "What's the best way to discover {name} in {habitat}?",
        "I've been mapping the {name} discoveries in {habitat}.",
        "The {name} is a mystery waiting to be found.",
        "I'm on a mission to discover every {name}.",
        "The {habitat} is a world of {name} discovery.",
        "I just discovered a new {name} behavior!",
        "The {name} is a true survivor of the unknown.",
        "What's the most exciting {name} discovery you've made?",
        "The {name} is a beacon of new beginnings.",
        "I've seen some incredible {name} sights.",
        "The {habitat} is a story of discovery, with {name}.",
        "I'm addicted to {name} discovery.",
        "The {name} is a symbol of finding.",
        "What's your favorite discovery memory?",
        "The {name} is a legend of the new.",
        "I've travelled far to discover this {name}.",
        "The {habitat} is my favorite place for discovery.",
        "I'm building a collection of {name} discoveries.",
        "The {name} is a star of the explorer world.",
        "What's the most challenging {name} to discover?",
        "The {name} is a reward for the persistent.",
        "I'm looking forward to my next discovery trip.",
        "The {habitat} is a treasure map for discovery.",
        "I've found a secret {name} spot!",
        "The {name} is a true pioneer.",
        "What's the best time for {name} discovery?",
        "The {name} is a beacon of the wilderness.",
        "I've documented over 50 new {name} sightings.",
        "The {habitat} is a world of wonder with {name}.",
        "I'm a certified {name} discoverer.",
        "The {name} is a symbol of the untamed.",
        "What's the furthest you've gone to discover a {name}?",
        "The {name} is a star of the map.",
        "I'm dedicated to discovering the rarest {name}.",
        "The {habitat} is a challenge, but {name} is worth it.",
        "I've seen {name} in places you wouldn't believe.",
        "The {name} is a legend of the discovery scene.",
        "What's the most exotic habitat you've discovered {name} in?",
        "The {name} is a beacon for the brave.",
        "I'm an expert at {name} discovery.",
        "The {habitat} is a story, and {name} is a chapter.",
        "I've found my first {name} and I'm hooked!",
        "The {name} is the heart of discovery."
    ],
    'STATISTICS': [
        "The stats for {name} are very interesting.",
        "What's the average BST for {name} in {habitat}?",
        "I've been analyzing the {name} data for weeks.",
        "The {name} is a star of the statistical report.",
        "How does {name} compare to the global average?",
        "I'm building a model for {name} population growth.",
        "The {name} is a beacon of numerical truth.",
        "What are the key statistical markers for {name}?",
        "I've seen some incredible {name} data sets.",
        "The {name} is a star of the analytics world.",
        "What's the best way to analyze {name} stats?",
        "I've been tracking {name} stats across all {habitat} regions.",
        "The {name} is a treasure trove of data.",
        "I'm on a mission to quantify every {name}.",
        "The {habitat} is a world of {name} statistics.",
        "I just found a new {name} stat trend!",
        "The {name} is a true survivor of the numbers.",
        "What's the most exciting {name} stat you've found?",
        "The {name} is a beacon of data-driven insights.",
        "I've seen some incredible {name} trends.",
        "The {habitat} is a story of statistics, with {name}.",
        "I'm addicted to {name} data analysis.",
        "The {name} is a symbol of precision.",
        "What's your favorite statistical memory?",
        "The {name} is a legend of the record.",
        "I've travelled far to collect {name} data.",
        "The {habitat} is my favorite place for stats.",
        "I'm building a database of {name} statistics.",
        "The {name} is a star of the researcher world.",
        "What's the most challenging {name} to quantify?",
        "The {name} is a reward for the meticulous.",
        "I'm looking forward to my next data collection trip.",
        "The {habitat} is a spreadsheet for {name} stats.",
        "I've found a secret {name} data cache!",
        "The {name} is a true pioneer of the numbers.",
        "What's the best time for {name} data collection?",
        "The {name} is a beacon of the wild data.",
        "I've documented over 100 {name} data points.",
        "The {habitat} is a world of wonder with {name} stats.",
        "I'm a certified {name} statistician.",
        "The {name} is a symbol of the quantified wild.",
        "What's the furthest you've gone to get {name} stats?",
        "The {name} is a star of the report.",
        "I'm dedicated to quantifying the rarest {name}.",
        "The {habitat} is a challenge, but {name} data is worth it.",
        "I've seen {name} stats you wouldn't believe.",
        "The {name} is a legend of the analytics scene.",
        "What's the most exotic habitat you've collected {name} stats in?",
        "The {name} is a beacon for the precise.",
        "I'm an expert at {name} data visualization.",
        "The {habitat} is a story, and {name} data is a chapter.",
        "I've found my first {name} data set and I'm hooked!",
        "The {name} is the heart of statistics."
    ],
    'PROFILE': [
        "I love everything about the {name}!",
        "The {name} is my favorite creature in the {habitat}.",
        "I've been a fan of {name} since I started playing.",
        "The {name} is a star of the profile spotlight.",
        "What's your favorite thing about {name}?",
        "I'm building a profile for every {name} variant.",
        "The {name} is a beacon of personality.",
        "What are the key traits of {name} in {habitat}?",
        "I've seen some incredible {name} fan art.",
        "The {name} is a star of the community world.",
        "What's the best way to build a {name} profile?",
        "I've been tracking {name} lore across all regions.",
        "The {name} is a treasure trove of stories.",
        "I'm on a mission to profile every {name}.",
        "The {habitat} is a world of {name} profiles.",
        "I just found a new {name} fact!",
        "The {name} is a true survivor of the community.",
        "What's the most exciting {name} fact you've found?",
        "The {name} is a beacon of fan-driven insights.",
        "I've seen some incredible {name} fan stories.",
        "The {habitat} is a story of profiles, with {name}.",
        "I'm addicted to {name} lore.",
        "The {name} is a symbol of fan love.",
        "What's your favorite {name} memory?",
        "The {name} is a legend of the fan base.",
        "I've travelled far to learn about {name}.",
        "The {habitat} is my favorite place for {name} stories.",
        "I'm building a library of {name} profiles.",
        "The {name} is a star of the fan world.",
        "What's the most challenging {name} to profile?",
        "The {name} is a reward for the dedicated.",
        "I'm looking forward to my next {name} fan meet.",
        "The {habitat} is a scrap book for {name} profiles.",
        "I've found a secret {name} fan club!",
        "The {name} is a true pioneer of the fan base.",
        "What's the best time for {name} fan activities?",
        "The {name} is a beacon of the fan community.",
        "I've documented over 100 {name} fan creations.",
        "The {habitat} is a world of wonder with {name} profiles.",
        "I'm a certified {name} fan.",
        "The {name} is a symbol of the fan-made wild.",
        "What's the furthest you've gone to meet other {name} fans?",
        "The {name} is a star of the fan page.",
        "I'm dedicated to profiling the rarest {name}.",
        "The {habitat} is a challenge, but {name} lore is worth it.",
        "I've seen {name} fans you wouldn't believe.",
        "The {name} is a legend of the fan scene.",
        "What's the most exotic habitat you've profiled {name} in?",
        "The {name} is a beacon for the fans.",
        "I'm an expert at {name} fan theory.",
        "The {habitat} is a story, and {name} lore is a chapter.",
        "I've found my first {name} fan group and I'm hooked!",
        "The {name} is the heart of the community."
    ],
    'OPINION': [
        "I think {name} is totally underrated.",
        "What's your hot take on {name} in the {habitat}?",
        "I disagree with the common opinion on {name}.",
        "The {name} is a star of the opinion piece.",
        "How do you feel about {name}'s current state?",
        "I'm writing a review of {name} for my blog.",
        "The {name} is a beacon of debate.",
        "What are the key points of contention regarding {name}?",
        "I've seen some heated {name} discussions.",
        "The {name} is a star of the forum world.",
        "What's the best way to voice an opinion on {name}?",
        "I've been tracking {name} opinions across all sites.",
        "The {name} is a treasure trove of viewpoints.",
        "I'm on a mission to hear every {name} opinion.",
        "The {habitat} is a world of {name} opinions.",
        "I just found a new {name} opinion trend!",
        "The {name} is a true survivor of the discourse.",
        "What's the most controversial {name} opinion you've heard?",
        "The {name} is a beacon of player-driven insights.",
        "I've seen some incredible {name} arguments.",
        "The {habitat} is a story of opinions, with {name}.",
        "I'm addicted to {name} discourse.",
        "The {name} is a symbol of player voice.",
        "What's your favorite opinionated memory?",
        "The {name} is a legend of the debate hall.",
        "I've travelled far to hear {name} opinions.",
        "The {habitat} is my favorite place for {name} talk.",
        "I'm building an archive of {name} opinions.",
        "The {name} is a star of the critic world.",
        "What's the most challenging {name} to review?",
        "The {name} is a reward for the thoughtful.",
        "I'm looking forward to my next {name} debate.",
        "The {habitat} is an editorial for {name} opinions.",
        "I've found a secret {name} think tank!",
        "The {name} is a true pioneer of the discourse.",
        "What's the best time for {name} discussions?",
        "The {name} is a beacon of the critical community.",
        "I've documented over 100 {name} reviews.",
        "The {habitat} is a world of wonder with {name} opinions.",
        "I'm a certified {name} critic.",
        "The {name} is a symbol of the critical wild.",
        "What's the furthest you've gone to voice an opinion on {name}?",
        "The {name} is a star of the op-ed.",
        "I'm dedicated to reviewing the rarest {name}.",
        "The {habitat} is a challenge, but {name} opinions are worth it.",
        "I've seen {name} critics you wouldn't believe.",
        "The {name} is a legend of the opinion scene.",
        "What's the most exotic habitat you've reviewed {name} in?",
        "The {name} is a beacon for the critical.",
        "I'm an expert at {name} analysis.",
        "The {habitat} is a story, and {name} opinions are a chapter.",
        "I've found my first {name} review group and I'm hooked!",
        "The {name} is the heart of the discourse."
    ],
    'GENERAL': [
        "Just saw a {name} and thought of this article.",
        "The {name} is so iconic.",
        "I love the {habitat}!",
        "Great read about the {name}.",
        "Thanks for sharing this {name} info.",
        "The {name} is truly one of a kind.",
        "I'm always excited for {name} news.",
        "The {habitat} is my happy place.",
        "Does anyone have a {name} for trade?",
        "The {name} is so cool!",
        "I just love this game.",
        "The {name} is a masterpiece.",
        "What's next for {name}?",
        "The {habitat} is stunning.",
        "I'm a proud {name} owner.",
        "The {name} is a star.",
        "I've learned so much today.",
        "The {name} is a legend.",
        "The {habitat} is so immersive.",
        "I'm addicted to this game.",
        "The {name} is the best.",
        "What's your favorite {habitat}?",
        "The {name} is so unique.",
        "I'm a {name} fan for life.",
        "The {habitat} is full of life.",
        "I just can't get enough of {name}.",
        "The {name} is a true gem.",
        "The {habitat} is a world of wonder.",
        "I'm so glad I found this.",
        "The {name} is a star of the show.",
        "The {habitat} is a masterpiece.",
        "I'm a {name} expert now.",
        "The {name} is a beacon of fun.",
        "The {habitat} is my second home.",
        "I'm so proud of my {name}.",
        "The {name} is a true companion.",
        "The {habitat} is a gift.",
        "I'm a {name} enthusiast.",
        "The {name} is a treasure.",
        "The {habitat} is a dream.",
        "I'm a {name} collector.",
        "The {name} is a symbol of joy.",
        "The {habitat} is a wonder.",
        "I'm a {name} lover.",
        "The {name} is a star of the world.",
        "The {habitat} is a story.",
        "I'm a {name} believer.",
        "The {name} is a legend of the wild.",
        "The {habitat} is a journey.",
        "I'm a {name} supporter.",
        "The {name} is the heart of the game.",
        "The {habitat} is everything.",
        "I love {name}!"
    ]
}

# Load current news_config.json
with open('assets/news_config.json', 'r', encoding='utf-8') as f:
    config = json.load(f)

# Update comment_templates
config['comment_templates'] = templates

# Save back to news_config.json
with open('assets/news_config.json', 'w', encoding='utf-8') as f:
    json.dump(config, f, indent=2, ensure_ascii=False)

print("Successfully updated comment templates with 50+ entries per category.")
